GET {local}api/item?id=99
Accept: application/json


###
@local =http://127.0.0.1:8000
# @name Register
POST {{local}}/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "zar",
    "email": "zar1@gmail.com",
    "password": "Todo!2024."
}

###
# @name Login
POST {{local}}/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "zar1@gmail.com",
    "password": "Todo!2024."
}

### Type status[Pending,In progress,Completed]
# @name Save Tasks
POST {{local}}/api/tasks/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|DHuU6pFDO86K2g1yNy84QxJSUbECAjp4eMtTMqad45a7851e

{
    "title": "complete App",
    "description": "complete the application in progress",
    "status": "In progress"
}


### Type status[Pending,In progress,Completed]
# @name Update Tasks
PUT {{local}}/api/tasks/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|DHuU6pFDO86K2g1yNy84QxJSUbECAjp4eMtTMqad45a7851e

{
    "task_id": 2,
    "title": "complet2e App",
    "description": "complet2e the application in progress",
    "status": "Completed"
}

###
# @name Deleted Tasks
DELETE {{local}}/api/tasks/delete
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|DHuU6pFDO86K2g1yNy84QxJSUbECAjp4eMtTMqad45a7851e

{
    "task_id": 1
}
